spring.application.name=freelancehub
server.port=8080

# Base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lkicfvrdswkqtztrdohc
spring.datasource.password=FreelanceHub123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=CAMBIAR_POR_UN_SECRETO_LARGO_PARA_DESARROLLO_FREELANCEHUB_2026
jwt.expiration=86400000

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Jackson
spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.freelancehub=DEBUG
